@baseUrl = http://localhost:3000
@country = brazil
GET {{baseUrl}}/lastSixMonths

###
GET https://api.covid19api.com/country/{{country}}/status/confirmed?from=2020-11-20T00:00:00Z&to=2021-05-20T00:00:00Z

###
GET https://api.covid19api.com/country/brazil/status/confirmed/live?from=2021-05-19T00:00:00Z&to=2021-05-20T23:59:59Z

###
GET https://api.covid19api.com/country/{{country}}/status/deaths?from=2021-04-01T00:00:00Z&to=2021-04-30T00:00:00Z